# Generated by Django 3.2.2 on 2021-08-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210805_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='response',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='response',
            name='likes',
        ),
    ]
