# Generated by Django 3.2.2 on 2021-08-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210809_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='filepath',
        ),
    ]
