# Generated by Django 3.2.2 on 2021-08-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_response_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='pdf',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
