# Generated by Django 3.2.2 on 2021-08-24 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_response_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='pdf',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
