# Generated by Django 3.2.2 on 2021-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_siteusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
