# Generated by Django 3.2.2 on 2021-09-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_siteusers_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteusers',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
