# Generated by Django 3.2.2 on 2021-09-01 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0017_siteusers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteusers',
            name='program',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='siteusers',
            name='pro_pic',
            field=models.ImageField(blank=True, default='user-3.png', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='siteusers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
