# Generated by Django 3.2.2 on 2021-09-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210901_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusers',
            name='pro_pic',
            field=models.ImageField(blank=True, default='images/user-3.png', null=True, upload_to='media'),
        ),
    ]
